### ISSUE TITLE
No " yeoboseyo " Mastodon app created

### ISSUE THREAD

**Issue by buzzworkers** [foxmask/yeoboseyo#13]
I followed the instruction, got a token generated by the correct login information in yeoboseyo_clientcred.secret file but I don't see any app created from this operation.
 
So I created an app myself via the Mastodon interface and stored the app token in the yeoboseyo_clientcred.secret file.
![image](https://user-images.githubusercontent.com/1935695/95687320-262f4780-0c03-11eb-9997-59e401053f6b.png)

Is that Okay ? will it be enough to have Mastodon to work ?

**Comment by foxmask** [comment]
yes, and in return you should have a file name yeoboseyo_clientcred.secret  with the token and the URL of the mastodon instance

**Comment by buzzworkers** [comment]
That part worked, but no app was ever created in the mastodon account from executing : **python3 mastodon_create_app.py**
maybe it's normal ?

**Comment by foxmask** [comment]
create an app "yeoboseyo" and validate the new app and that's all
then the script will exchange token and store in the secret file

**Comment by buzzworkers** [comment]
OK so I misunderstood, I thought the command would create the app on its own, sorry, this can be closed :+1:

**Comment by foxmask** [comment]
I will add it to the README

**Comment by buzzworkers** [comment]
what got me confused was this line in the readme :
![image](https://user-images.githubusercontent.com/1935695/95687797-30067a00-0c06-11eb-8925-740ce30a04ac.png)

**Comment by foxmask** [comment]
but it's a mistake
