### ISSUE TITLE
Service never triggered when date is None

### ISSUE THREAD

**Issue by foxmask** [foxmask/yeoboseyo#3]

**Comment by Extomvi** [comment]
what is required to do and perform?

**Comment by foxmask** [comment]
hi @Extomvi 
nothing :) 
I set a default value when creating on tirgger as you can see here https://github.com/foxmask/yeoboseyo/commit/847746310c0469aeb1b59ce6ecd0667c45a2d62f#diff-9a2d2d65ae3c83e37824d628ed481f85L29
